#ifndef CONFIGURATION_H_INCLUDED
#define CONFIGURATION_H_INCLUDED


#include "model/model.h"


void configuration_load(model_t *pmodel);


extern const char *CONFIGURATION_LANGUAGE_KEY;
extern const char *CONFIGURATION_BRIGHTNESS_KEY;
extern const char *CONFIGURATION_VOLUME_KEY;
extern const char *CONFIGURATION_EROGATION_1_PERCENTAGE_KEY;
extern const char *CONFIGURATION_EROGATION_2_PERCENTAGE_KEY;
extern const char *CONFIGURATION_SCHEDULER_ENTRIES_KEYS[NUM_EROGATORS][NUM_PROGRAMS];
extern const char *CONFIGURATION_SCHEDULER_WM_KEYS[NUM_EROGATORS][NUM_PROGRAMS];
extern const char *CONFIGURATION_SCHEDULER_ACTIVE_TIME_KEYS[NUM_EROGATORS][NUM_PROGRAMS];
extern const char *CONFIGURATION_SCHEDULER_PAUSE_TIME_KEYS[NUM_EROGATORS][NUM_PROGRAMS];


#endif