#ifndef AUTOGEN_FILE_STRINGS_H_INCLUDED
#define AUTOGEN_FILE_STRINGS_H_INCLUDED

typedef enum {
    STRINGS_LINGUA = 0,
    STRINGS_DISPLAY,
    STRINGS_VOLUME,
    STRINGS_GIORNO,
    STRINGS_ORA,
    STRINGS_PRODOTTO,
    STRINGS_MULTI_PROGRAMMA,
    STRINGS_MODIFICA,
    STRINGS_PROGRAMMA,
    STRINGS_PERC_PRODOTTO,
    STRINGS_LUN,
    STRINGS_MAR,
    STRINGS_MER,
    STRINGS_GIO,
    STRINGS_VEN,
    STRINGS_SAB,
    STRINGS_DOM,
    STRINGS_INIZIO,
    STRINGS_FINE,
    STRINGS_SECONDI,
    STRINGS_MINUTI,
} strings_t;

extern const char *strings[21][2];

#endif
